import { describe, expect, it } from 'vitest';
import {
  APPLICATION_COMMAND_OPTION_TYPE,
  APPLICATION_COMMAND_TYPE,
  AUTOMOD_ACTION_TYPE_VALUES,
  AUTOMOD_EVENT_TYPE_VALUES,
  AUTOMOD_TRIGGER_TYPE_VALUES,
  CHANNEL_TYPE_VALUES,
  FORUM_LAYOUT_TYPE,
  INTERACTION_RESPONSE_TYPE,
  PERMISSION_OVERWRITE_TYPE_VALUES,
  REACTION_TYPE,
  SCHEDULED_EVENT_ENTITY_TYPE,
  SCHEDULED_EVENT_PRIVACY_LEVEL,
  SCHEDULED_EVENT_STATUS,
  SORT_ORDER_TYPE,
  STICKER_FORMAT_TYPE,
  THREAD_AUTO_ARCHIVE_DURATION,
  VIDEO_QUALITY_MODE,
} from './discord-enums.js';

describe('discord-enums', () => {
  it('every constant is non-empty', () => {
    const all = [
      CHANNEL_TYPE_VALUES,
      PERMISSION_OVERWRITE_TYPE_VALUES,
      AUTOMOD_TRIGGER_TYPE_VALUES,
      AUTOMOD_EVENT_TYPE_VALUES,
      AUTOMOD_ACTION_TYPE_VALUES,
      SCHEDULED_EVENT_PRIVACY_LEVEL,
      SCHEDULED_EVENT_ENTITY_TYPE,
      SCHEDULED_EVENT_STATUS,
      APPLICATION_COMMAND_TYPE,
      APPLICATION_COMMAND_OPTION_TYPE,
      INTERACTION_RESPONSE_TYPE,
      STICKER_FORMAT_TYPE,
      FORUM_LAYOUT_TYPE,
      SORT_ORDER_TYPE,
      VIDEO_QUALITY_MODE,
      REACTION_TYPE,
      THREAD_AUTO_ARCHIVE_DURATION,
    ];
    for (const arr of all) {
      expect(arr.length).toBeGreaterThan(0);
    }
  });

  it('CHANNEL_TYPE_VALUES covers known types', () => {
    expect(CHANNEL_TYPE_VALUES).toContain(0); // GUILD_TEXT
    expect(CHANNEL_TYPE_VALUES).toContain(15); // GUILD_FORUM
  });

  it('STICKER_FORMAT_TYPE has 4 entries (PNG, APNG, LOTTIE, GIF)', () => {
    expect(STICKER_FORMAT_TYPE).toEqual([1, 2, 3, 4]);
  });

  it('THREAD_AUTO_ARCHIVE_DURATION matches Discord allowed values', () => {
    expect(THREAD_AUTO_ARCHIVE_DURATION).toEqual([60, 1440, 4320, 10080]);
  });
});
